version: '3.8'
services:
  echo-server:
    image: landrzejewski/echo-server:v2
    restart: always
    deploy:
      replicas: 3	
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=training
